const emojis = [
  // Smileys & Emotion
  { emoji: "😀", name: "grinning face", category: "smileys" },
  { emoji: "😃", name: "grinning face with big eyes", category: "smileys" },
  { emoji: "😄", name: "grinning face with smiling eyes", category: "smileys" },
  { emoji: "😁", name: "beaming face with smiling eyes", category: "smileys" },
  { emoji: "😆", name: "grinning squinting face", category: "smileys" },
  { emoji: "😅", name: "grinning face with sweat", category: "smileys" },
  { emoji: "😂", name: "face with tears of joy", category: "smileys" },
  { emoji: "🤣", name: "rolling on the floor laughing", category: "smileys" },
  { emoji: "😊", name: "smiling face with smiling eyes", category: "smileys" },
  { emoji: "😇", name: "smiling face with halo", category: "smileys" },
  { emoji: "🙂", name: "slightly smiling face", category: "smileys" },
  { emoji: "🙃", name: "upside-down face", category: "smileys" },
  { emoji: "😉", name: "winking face", category: "smileys" },
  { emoji: "😌", name: "relieved face", category: "smileys" },
  { emoji: "😍", name: "smiling face with heart-eyes", category: "smileys" },
  { emoji: "😘", name: "face blowing a kiss", category: "smileys" },
  { emoji: "😗", name: "kissing face", category: "smileys" },
  { emoji: "😙", name: "kissing face with smiling eyes", category: "smileys" },
  { emoji: "😚", name: "kissing face with closed eyes", category: "smileys" },
  { emoji: "😋", name: "face savoring food", category: "smileys" },
    { emoji: "🤗", name: "hugging face", category: "smileys" },
  { emoji: "🤔", name: "thinking face", category: "smileys" },
  { emoji: "🤭", name: "face with hand over mouth", category: "smileys" },
  { emoji: "🤫", name: "shushing face", category: "smileys" },
  { emoji: "🤥", name: "lying face", category: "smileys" },
  { emoji: "😶", name: "face without mouth", category: "smileys" },
  { emoji: "😐", name: "neutral face", category: "smileys" },
  { emoji: "😑", name: "expressionless face", category: "smileys" },
  { emoji: "😒", name: "unamused face", category: "smileys" },
  { emoji: "🙁", name: "slightly frowning face", category: "smileys" },
  { emoji: "☹️", name: "frowning face", category: "smileys" },
  { emoji: "😔", name: "pensive face", category: "smileys" },
  { emoji: "😕", name: "confused face", category: "smileys" },
  { emoji: "😖", name: "confounded face", category: "smileys" },
  { emoji: "😞", name: "disappointed face", category: "smileys" },
  { emoji: "😟", name: "worried face", category: "smileys" },
  { emoji: "😢", name: "crying face", category: "smileys" },
  { emoji: "😭", name: "loudly crying face", category: "smileys" },
  { emoji: "😦", name: "frowning face with open mouth", category: "smileys" },
  { emoji: "😧", name: "anguished face", category: "smileys" },


  // Animals & Nature
  { emoji: "🐶", name: "dog", category: "animals" },
  { emoji: "🐱", name: "cat", category: "animals" },
  { emoji: "🐭", name: "mouse", category: "animals" },
  { emoji: "🐹", name: "hamster", category: "animals" },
  { emoji: "🐰", name: "rabbit", category: "animals" },
  { emoji: "🦊", name: "fox", category: "animals" },
  { emoji: "🐻", name: "bear", category: "animals" },
  { emoji: "🐼", name: "panda", category: "animals" },
  { emoji: "🐨", name: "koala", category: "animals" },
  { emoji: "🐯", name: "tiger", category: "animals" },
  { emoji: "🦁", name: "lion", category: "animals" },
  { emoji: "🐮", name: "cow", category: "animals" },
  { emoji: "🐷", name: "pig", category: "animals" },
  { emoji: "🐸", name: "frog", category: "animals" },
  { emoji: "🐵", name: "monkey", category: "animals" },
   { emoji: "🦝", name: "raccoon", category: "animals" },
  { emoji: "🦨", name: "skunk", category: "animals" },
  { emoji: "🦡", name: "badger", category: "animals" },
  { emoji: "🦦", name: "otter", category: "animals" },
  { emoji: "🦥", name: "sloth", category: "animals" },
  { emoji: "🦫", name: "beaver", category: "animals" },
  { emoji: "🦘", name: "kangaroo", category: "animals" },
  { emoji: "🦃", name: "turkey", category: "animals" },
  { emoji: "🐓", name: "rooster", category: "animals" },
  { emoji: "🦚", name: "peacock", category: "animals" },
  { emoji: "🦜", name: "parrot", category: "animals" },
  { emoji: "🦢", name: "swan", category: "animals" },
  { emoji: "🦩", name: "flamingo", category: "animals" },
  { emoji: "🕊️", name: "dove", category: "animals" },
  { emoji: "🦉", name: "owl", category: "animals" },
  { emoji: "🦇", name: "bat", category: "animals" },
  { emoji: "🐺", name: "wolf", category: "animals" },
  { emoji: "🦈", name: "shark", category: "animals" },
  { emoji: "🐬", name: "dolphin", category: "animals" },
  { emoji: "🐳", name: "spouting whale", category: "animals" },

  // Food & Drink
  { emoji: "🍏", name: "green apple", category: "food" },
  { emoji: "🍎", name: "red apple", category: "food" },
  { emoji: "🍐", name: "pear", category: "food" },
  { emoji: "🍊", name: "tangerine", category: "food" },
  { emoji: "🍋", name: "lemon", category: "food" },
  { emoji: "🍌", name: "banana", category: "food" },
  { emoji: "🍉", name: "watermelon", category: "food" },
  { emoji: "🍇", name: "grapes", category: "food" },
  { emoji: "🍓", name: "strawberry", category: "food" },
  { emoji: "🫐", name: "blueberries", category: "food" },
  { emoji: "🍈", name: "melon", category: "food" },
  { emoji: "🍒", name: "cherries", category: "food" },
  { emoji: "🍑", name: "peach", category: "food" },
  { emoji: "🥭", name: "mango", category: "food" },
  { emoji: "🍍", name: "pineapple", category: "food" },
  { emoji: "🥥", name: "coconut", category: "food" },
  { emoji: "🥝", name: "kiwi", category: "food" },
  { emoji: "🍅", name: "tomato", category: "food" },
  { emoji: "🥑", name: "avocado", category: "food" },
  { emoji: "🥦", name: "broccoli", category: "food" },
  { emoji: "🥬", name: "leafy green", category: "food" },
  { emoji: "🥒", name: "cucumber", category: "food" },
  { emoji: "🌶️", name: "hot pepper", category: "food" },
  { emoji: "🌽", name: "corn", category: "food" },
  { emoji: "🥕", name: "carrot", category: "food" },
  { emoji: "🫑", name: "bell pepper", category: "food" },
  { emoji: "🥔", name: "potato", category: "food" },
  { emoji: "🍠", name: "sweet potato", category: "food" },
  { emoji: "🥐", name: "croissant", category: "food" },
  { emoji: "🍞", name: "bread", category: "food" },
  { emoji: "🥖", name: "baguette", category: "food" },
  { emoji: "🫓", name: "flatbread", category: "food" },
  { emoji: "🥨", name: "pretzel", category: "food" },
  { emoji: "🥯", name: "bagel", category: "food" },
  { emoji: "🥞", name: "pancakes", category: "food" },
  { emoji: "🧇", name: "waffle", category: "food" },
  { emoji: "🧈", name: "butter", category: "food" },
  { emoji: "🧀", name: "cheese", category: "food" },
  { emoji: "🍖", name: "meat on bone", category: "food" },
  { emoji: "🍗", name: "poultry leg", category: "food" },
  { emoji: "🥩", name: "cut of meat", category: "food" },
  { emoji: "🥓", name: "bacon", category: "food" },
  { emoji: "🍔", name: "hamburger", category: "food" },
  { emoji: "🍟", name: "french fries", category: "food" },
  { emoji: "🍕", name: "pizza", category: "food" },
  { emoji: "🌭", name: "hot dog", category: "food" },
  { emoji: "🥪", name: "sandwich", category: "food" },
  { emoji: "🌮", name: "taco", category: "food" },
  { emoji: "🌯", name: "burrito", category: "food" },
  { emoji: "🫔", name: "tamale", category: "food" },
  { emoji: "🥗", name: "green salad", category: "food" },
  { emoji: "🥘", name: "shallow pan of food", category: "food" },
  { emoji: "🥫", name: "canned food", category: "food" },
  { emoji: "🍝", name: "spaghetti", category: "food" },
  { emoji: "🍜", name: "steaming bowl", category: "food" },
  { emoji: "🍲", name: "pot of food", category: "food" },
  { emoji: "🍛", name: "curry rice", category: "food" },
  { emoji: "🍣", name: "sushi", category: "food" },
  { emoji: "🍱", name: "bento box", category: "food" },
  { emoji: "🥟", name: "dumpling", category: "food" },
  { emoji: "🦪", name: "oyster", category: "food" },
    { emoji: "🥚", name: "egg", category: "food" },
  { emoji: "🧄", name: "garlic", category: "food" },
  { emoji: "🧅", name: "onion", category: "food" },
  { emoji: "🥜", name: "peanuts", category: "food" },
  { emoji: "🌰", name: "chestnut", category: "food" },
  { emoji: "🥯", name: "bagel", category: "food" },
  { emoji: "🥨", name: "pretzel", category: "food" },
  { emoji: "🧆", name: "falafel", category: "food" },
  { emoji: "🥩", name: "steak", category: "food" },
  { emoji: "🥓", name: "bacon", category: "food" },
  { emoji: "🥚", name: "egg", category: "food" },
  { emoji: "🥞", name: "pancakes", category: "food" },
  { emoji: "🧇", name: "waffle", category: "food" },
  { emoji: "🍤", name: "fried shrimp", category: "food" },
  { emoji: "🦀", name: "crab", category: "food" },
  { emoji: "🦞", name: "lobster", category: "food" },
  { emoji: "🦐", name: "shrimp", category: "food" },
  { emoji: "🦑", name: "squid", category: "food" },
  { emoji: "🍱", name: "bento box", category: "food" },
  { emoji: "🥡", name: "takeout box", category: "food" },
  

  // Activities
  { emoji: "⚽", name: "soccer ball", category: "activities" },
  { emoji: "🏀", name: "basketball", category: "activities" },
  { emoji: "🏈", name: "american football", category: "activities" },
  { emoji: "⚾", name: "baseball", category: "activities" },
  { emoji: "🎾", name: "tennis", category: "activities" },
  { emoji: "🏐", name: "volleyball", category: "activities" },
  { emoji: "🏉", name: "rugby football", category: "activities" },
  { emoji: "🥏", name: "flying disc", category: "activities" },
  { emoji: "🎱", name: "billiards", category: "activities" },
  { emoji: "🏓", name: "table tennis", category: "activities" },
  { emoji: "🏸", name: "badminton", category: "activities" },
  { emoji: "🥅", name: "goal net", category: "activities" },
  { emoji: "⛳", name: "golf", category: "activities" },
  { emoji: "🏹", name: "bow and arrow", category: "activities" },
  { emoji: "🎣", name: "fishing pole", category: "activities" },
    { emoji: "🥊", name: "boxing glove", category: "activities" },
  { emoji: "🥋", name: "martial arts uniform", category: "activities" },
  { emoji: "⛸️", name: "ice skate", category: "activities" },
  { emoji: "🥌", name: "curling stone", category: "activities" },
  { emoji: "🎿", name: "ski", category: "activities" },
  { emoji: "🛷", name: "sled", category: "activities" },
  { emoji: "🏂", name: "snowboarder", category: "activities" },
  { emoji: "🏋️", name: "weightlifter", category: "activities" },
  { emoji: "🤸", name: "person cartwheeling", category: "activities" },
  { emoji: "🤾", name: "person playing handball", category: "activities" },
  { emoji: "🏇", name: "horse racing", category: "activities" },
  { emoji: "🏄", name: "person surfing", category: "activities" },
  { emoji: "🏊", name: "person swimming", category: "activities" },
  { emoji: "🤽", name: "person playing water polo", category: "activities" },
  { emoji: "🚣", name: "person rowing boat", category: "activities" },
  { emoji: "🧗", name: "person climbing", category: "activities" },
  { emoji: "🚵", name: "person mountain biking", category: "activities" },
  { emoji: "🚴", name: "person biking", category: "activities" },
  { emoji: "🤹", name: "person juggling", category: "activities" },
  { emoji: "🎪", name: "circus tent", category: "activities" },


  // Travel & Places
  { emoji: "✈️", name: "airplane", category: "travel" },
  { emoji: "🚗", name: "car", category: "travel" },
  { emoji: "🚕", name: "taxi", category: "travel" },
  { emoji: "🚙", name: "suv", category: "travel" },
  { emoji: "🚌", name: "bus", category: "travel" },
  { emoji: "🚎", name: "trolleybus", category: "travel" },
  { emoji: "🏎️", name: "race car", category: "travel" },
  { emoji: "🚓", name: "police car", category: "travel" },
  { emoji: "🚑", name: "ambulance", category: "travel" },
  { emoji: "🚒", name: "fire engine", category: "travel" },
  { emoji: "🚜", name: "tractor", category: "travel" },
  { emoji: "🚲", name: "bicycle", category: "travel" },
  { emoji: "🛴", name: "scooter", category: "travel" },
  { emoji: "🛵", name: "motor scooter", category: "travel" },
  { emoji: "🏍️", name: "motorcycle", category: "travel" },
  { emoji: "🚤", name: "speedboat", category: "travel" },
  { emoji: "⛵", name: "sailboat", category: "travel" },
  { emoji: "🛶", name: "canoe", category: "travel" },
  { emoji: "🚢", name: "ship", category: "travel" },
  { emoji: "🛳️", name: "passenger ship", category: "travel" },
  { emoji: "🚁", name: "helicopter", category: "travel" },
  { emoji: "🛰️", name: "satellite", category: "travel" },
  { emoji: "🚂", name: "locomotive", category: "travel" },
  { emoji: "🚆", name: "train", category: "travel" },
  { emoji: "🚇", name: "metro", category: "travel" },
  { emoji: "🚊", name: "tram", category: "travel" },
  { emoji: "🚝", name: "monorail", category: "travel" },
  { emoji: "🛤️", name: "railway track", category: "travel" },
  { emoji: "🛣️", name: "motorway", category: "travel" },
  { emoji: "🛢️", name: "oil drum", category: "travel" },
  { emoji: "⛽", name: "fuel pump", category: "travel" },
  { emoji: "🚏", name: "bus stop", category: "travel" },
  { emoji: "🗺️", name: "world map", category: "travel" },
  { emoji: "🗿", name: "moai", category: "travel" },

  // Objects
  { emoji: "💡", name: "light bulb", category: "objects" },
  { emoji: "🔑", name: "key", category: "objects" },
  { emoji: "🪑", name: "chair", category: "objects" },
  { emoji: "🛏️", name: "bed", category: "objects" },
  { emoji: "🚪", name: "door", category: "objects" },
  { emoji: "🪞", name: "mirror", category: "objects" },
  { emoji: "🖼️", name: "frame", category: "objects" },
  { emoji: "🛋️", name: "couch", category: "objects" },
  { emoji: "🪟", name: "window", category: "objects" },
  { emoji: "📱", name: "mobile phone", category: "objects" },
  { emoji: "💻", name: "laptop", category: "objects" },
  { emoji: "🖨️", name: "printer", category: "objects" },
  { emoji: "🕹️", name: "joystick", category: "objects" },
  { emoji: "🎮", name: "video game", category: "objects" },
  { emoji: "⌚", name: "watch", category: "objects" },
  { emoji: "🔨", name: "hammer", category: "objects" },
  { emoji: "⛏️", name: "pick", category: "objects" },
  { emoji: "⚒️", name: "hammer and pick", category: "objects" },
  { emoji: "🛠️", name: "hammer and wrench", category: "objects" },
  { emoji: "🗡️", name: "dagger", category: "objects" },
  { emoji: "⚔️", name: "crossed swords", category: "objects" },
  { emoji: "🏹", name: "bow and arrow", category: "objects" },
  { emoji: "🛡️", name: "shield", category: "objects" },
  { emoji: "🔧", name: "wrench", category: "objects" },
  { emoji: "🔩", name: "nut and bolt", category: "objects" },
  { emoji: "⚙️", name: "gear", category: "objects" },
  { emoji: "🪛", name: "screwdriver", category: "objects" },
  { emoji: "🪜", name: "ladder", category: "objects" },
  { emoji: "🏗️", name: "building construction", category: "objects" },
  { emoji: "🧰", name: "toolbox", category: "objects" },
  { emoji: "🧲", name: "magnet", category: "objects" },
  { emoji: "💣", name: "bomb", category: "objects" },
  { emoji: "🪤", name: "mouse trap", category: "objects" },
  { emoji: "🪙", name: "coin", category: "objects" },
  { emoji: "💎", name: "gem stone", category: "objects" },

  // Symbols
  { emoji: "❤️", name: "red heart", category: "symbols" },
  { emoji: "🧡", name: "orange heart", category: "symbols" },
  { emoji: "💛", name: "yellow heart", category: "symbols" },
  { emoji: "💚", name: "green heart", category: "symbols" },
  { emoji: "💙", name: "blue heart", category: "symbols" },
  { emoji: "💜", name: "purple heart", category: "symbols" },
  { emoji: "🖤", name: "black heart", category: "symbols" },
  { emoji: "🤍", name: "white heart", category: "symbols" },
  { emoji: "💔", name: "broken heart", category: "symbols" },
  { emoji: "✨", name: "sparkles", category: "symbols" },
  { emoji: "⚡", name: "high voltage", category: "symbols" },
  { emoji: "🔥", name: "fire", category: "symbols" },
  { emoji: "⭐", name: "star", category: "symbols" },
  { emoji: "🌟", name: "glowing star", category: "symbols" },
  { emoji: "☀️", name: "sun", category: "symbols" },
  { emoji: "🌤️", name: "sun behind small cloud", category: "symbols" },
  { emoji: "⛅", name: "sun behind cloud", category: "symbols" },
  { emoji: "🌥️", name: "sun behind large cloud", category: "symbols" },
  { emoji: "☁️", name: "cloud", category: "symbols" },
  { emoji: "🌧️", name: "cloud with rain", category: "symbols" },
  { emoji: "⛈️", name: "cloud with lightning and rain", category: "symbols" },
  { emoji: "🌩️", name: "cloud with lightning", category: "symbols" },
  { emoji: "🌨️", name: "cloud with snow", category: "symbols" },
  { emoji: "❄️", name: "snowflake", category: "symbols" },
  { emoji: "☃️", name: "snowman", category: "symbols" },
  { emoji: "⛄", name: "snowman without snow", category: "symbols" },
  { emoji: "🌪️", name: "tornado", category: "symbols" },
  { emoji: "🌫️", name: "fog", category: "symbols" },
  { emoji: "💨", name: "dash", category: "symbols" },
  { emoji: "💫", name: "dizzy", category: "symbols" },
  { emoji: "☂️", name: "umbrella", category: "symbols" },
  { emoji: "☔", name: "umbrella with rain drops", category: "symbols" },
  { emoji: "⚓", name: "anchor", category: "symbols" },

  // Flags (sample)
  { emoji: "🇺🇸", name: "flag: United States", category: "flags" },
  { emoji: "🇬🇧", name: "flag: United Kingdom", category: "flags" },
  { emoji: "🇮🇳", name: "flag: India", category: "flags" },
  { emoji: "🇨🇦", name: "flag: Canada", category: "flags" },
  { emoji: "🇦🇺", name: "flag: Australia", category: "flags" },
  { emoji: "🇯🇵", name: "flag: Japan", category: "flags" },
  { emoji: "🇰🇷", name: "flag: South Korea", category: "flags" },
  { emoji: "🇩🇪", name: "flag: Germany", category: "flags" },
  { emoji: "🇫🇷", name: "flag: France", category: "flags" },
  { emoji: "🇮🇹", name: "flag: Italy", category: "flags" }
];

